name: Build, Scan, and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t azuresubha/phpwebsite01:latest .

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        trivy-version: '0.18.3'
        
    - name: Scan Docker image with Trivy
      id: trivy-scan
      run: |
        trivy image --exit-code 1 --severity CRITICAL azuresubha/phpwebsite01:latest
        if [ $? -ne 0 ]; then
          echo "Vulnerabilities found in the image"
          exit 1
        fi

    - name: Log in to Docker Hub
      if: steps.trivy-scan.outcome == 'success'
      run: docker login -u azuresubha -p ${{ secrets.DOCKER_PAT }}

    - name: Push Docker image
      if: steps.trivy-scan.outcome == 'success'
      run: docker push azuresubha/phpwebsite01:latest
