
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t azuresubha/phpwebsite01:latest  .

    - name: Log in to Docker Hub
      run: docker login -u azuresubha -p ${{ secrets.DOCKER_PAT }}

    - name: Push Docker image
      run: docker push azuresubha/phpwebsite01:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        password: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Stop and remove the previous running container
          docker stop phpwebsite01 || true
          docker rm phpwebsite01 || true
          # Delete the previous image
          docker rmi azuresubha/phpwebsite01:previous || true
          # Pull and run the updated image
          docker pull azuresubha/phpwebsite01:latest
          docker run -d -p 80:80 --name phpwebsite01 azuresubha/phpwebsite01:latest
