name: Build, Scan, and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t azuresubha/phpwebsite01:latest .

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        version: '0.60.0'
        
    - name: Scan Docker image with Trivy
      id: trivy-scan
      run: |
        # Scan with detailed output but only fail on CRITICAL
        trivy image --format table --exit-code 1 --severity CRITICAL azuresubha/phpwebsite01:latest

    - name: Notify on failure
      if: failure() && steps.trivy-scan.outcome == 'failure'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🚨 Trivy Scan Failed for azuresubha/phpwebsite01"
        to: subha4256@gmail.com
        from: GitHub Actions
        body: |
          Trivy scan failed during CI/CD pipeline.
          
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Workflow: ${{ github.workflow }}
          
          Please check the workflow run for details:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Log in to Docker Hub
      if: steps.trivy-scan.outcome == 'success'
      run: docker login -u azuresubha -p ${{ secrets.DOCKER_PAT }}

    - name: Push Docker image
      if: steps.trivy-scan.outcome == 'success'
      run: docker push azuresubha/phpwebsite01:latest
