name: Build, Scan, and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t azuresubha/phpwebsite01:latest .

    - name: Setup Trivy (v0.60.0)
      uses: aquasecurity/trivy-action@master
      with:
        version: '0.60.0'  # Explicitly specifying v0.60.0
        
    - name: Scan Docker image
      id: trivy-scan
      run: |
        # Scan with table output, fail only on CRITICAL vulnerabilities
        trivy image \
          --format table \
          --exit-code 1 \
          --severity CRITICAL \
          --ignore-unfixed \
          azuresubha/phpwebsite01:latest

    - name: Notify on Scan Failure
      if: failure() && steps.trivy-scan.outcome == 'failure'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Trivy Scan FAILED: azuresubha/phpwebsite01"
        to: subha4256@gmail.com
        from: GitHub Actions
        body: |
         Critical vulnerabilities detected in Docker image!
          
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Run ID: ${{ github.run_id }}
          
          View failed workflow:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          Please investigate immediately.

    - name: Login to Docker Hub
      if: steps.trivy-scan.outcome == 'success'
      run: docker login -u azuresubha -p ${{ secrets.DOCKER_PAT }}

    - name: Push to Docker Hub
      if: steps.trivy-scan.outcome == 'success'
      run: docker push azuresubha/phpwebsite01:latest
