name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yourusername/php-app:latest  # You can use any fixed tag or a custom tag here

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Stop and remove the previous running container
          docker stop php-app || true
          docker rm php-app || true

          # Delete the previous image
          docker rmi yourusername/php-app:previous || true

          # Pull and run the updated image
          docker pull yourusername/php-app:latest  # Use the same tag as specified in the build-push step
          docker run -d -p 80:80 --name php-app yourusername/php-app:latest
